flowchart TD
  %% Node Definitions:
  com.github.ferstl:compile["com.github.ferstl"]
  com.google.guava:compile["com.google.guava"]
  commons-codec:compile["commons-codec"]
  org.apache.commons:compile["org.apache.commons"]

  %% Edge Definitions:
  com.github.ferstl:compile --> com.google.guava:compile
  com.github.ferstl:compile --> commons-codec:compile
  com.github.ferstl:compile --> org.apache.commons:compile